### ISSUE TITLE
MatchText组件中，textStr更新组件不更新

### ISSUE THREAD

**Issue by 97Ronal** [dbwcooper/react-ctrl-f#1]
在MatchText组件中，当searchValue为空字符串的时候，修改textStr，组件不更新

**Comment by dbwcooper** [comment]
> 在MatchText组件中，当searchValue为空字符串的时候，修改textStr，组件不更新

已 merge。

**Comment by dbwcooper** [comment]
https://www.npmjs.com/package/react-ctrl-f ; released
