### ISSUE TITLE
bug - Invalid hook call

### ISSUE THREAD

**Issue by targhs** [dbwcooper/react-ctrl-f#3]
Using MatchText raises invalid hook call error.

Code
```
import React, { useContext } from "react";
import { Link } from "react-router-dom";

import {
  MatchText,
  SearchProvider,
  SearchContext,
  SearchEventContext,
} from "react-ctrl-f";

export default function Home() {
  return (
    <>
      <div>Home</div>
      <MatchText id='match-text-id-1'>Hello world</MatchText>
    </>
  );
}

```

As soon as i remove MatchText. Everything works fine. Am i missing something?

Versions using:
"react-ctrl-f": "^0.0.4"
"react": "^18.1.0"

**Comment by dbwcooper** [comment]
> Using MatchText raises invalid hook call error.
> 
> Code
> 
> ```
> import React, { useContext } from "react";
> import { Link } from "react-router-dom";
> 
> import {
>   MatchText,
>   SearchProvider,
>   SearchContext,
>   SearchEventContext,
> } from "react-ctrl-f";
> 
> export default function Home() {
>   return (
>     <>
>       <div>Home</div>
>       <MatchText id='match-text-id-1'>Hello world</MatchText>
>     </>
>   );
> }
> ```
> 
> As soon as i remove MatchText. Everything works fine. Am i missing something?
> 
> Versions using: "react-ctrl-f": "^0.0.4" "react": "^18.1.0"

React 18 is not supported for now

**Comment by targhs** [comment]
Okay. Thanks
